### ISSUE TITLE
Typo on "More resources"

### ISSUE THREAD

**Issue by masaldaan** [jakemcc/backgammon#2]
The URL to Eric Normand's site purelyfunctional.tv has a typo in it. I can submit a PR if there's a PPT/Keynote I can export PDF from. Apologies if this was too pedantic an issue to raise.

**Comment by jakemcc** [comment]
Thanks for pointing it out. I'm away from a computer now, but I'll just fix it when I get back on one.

**Comment by jakemcc** [comment]
Fixed.
